//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraper.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWebScrapingEntities : DbContext
    {
        public DBWebScrapingEntities()
            : base("name=DBWebScrapingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
        public virtual DbSet<ResultsDetail> ResultsDetails { get; set; }
        public virtual DbSet<ResultsHeader> ResultsHeaders { get; set; }
        public virtual DbSet<Selector> Selectors { get; set; }
    }
}
