//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class WebScraperDBEntities : DbContext
    {
        public WebScraperDBEntities()
            : base("name=WebScraperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [DataMember]
        public virtual DbSet<Page> Pages { get; set; }
        [DataMember]
        public virtual DbSet<Query> Queries { get; set; }
        [DataMember]
        public virtual DbSet<ResultsDetail> ResultsDetails { get; set; }
        [DataMember]
        public virtual DbSet<ResultsHeader> ResultsHeaders { get; set; }
        [DataMember]
        public virtual DbSet<Selector> Selectors { get; set; }
    }
}
